//! The host network setup transparent forwarding depends on, generated from
//! the gateway's own configuration so the port range and the marks can never
//! disagree between the config file and the firewall.
//!
//! ```text
//! mc-gateway --config config.yaml --print-network-setup | sh
//! ```
//!
//! How the rules work:
//!
//! * The gateway's transparent backend connections carry [`SOCKET_MARK`]. The
//!   `output` chain copies that onto the connection as [`CONN_MARK`].
//! * With interception, a new connection to a covered port is handed to the
//!   gateway's listener by `tproxy`, and gets [`CONN_MARK`] too.
//! * In `prerouting`, any packet of a connection carrying [`CONN_MARK`] — a
//!   backend's reply to the gateway, or the player's next packet on an
//!   intercepted connection — gets [`ROUTE_MARK`], which [`ROUTE_TABLE`] routes
//!   to the local stack, where the gateway's socket picks it up.
//!
//! The rules fail open. If the gateway is not listening, `tproxy` finds no
//! socket and does not match, so connections go straight to the server as if
//! the rules were not there.
//!
//! IPv4 only: IPv6 traffic passes through untouched.

use std::{fmt::Write, net::SocketAddr};

/// Set with `SO_MARK` on every transparent backend socket.
pub const SOCKET_MARK: u32 = 0x6d64;
/// Carried on conntrack entries the gateway is part of.
pub const CONN_MARK: u32 = 0x6d63;
/// Packet mark that selects [`ROUTE_TABLE`].
pub const ROUTE_MARK: u32 = 0x6d67;
/// Routing table whose only route delivers everything locally.
pub const ROUTE_TABLE: u32 = 6767;
/// nftables table name, owned entirely by the gateway.
pub const NFT_TABLE: &str = "mcgateway";

/// Ports to intercept, as inclusive ranges.
#[derive(Debug, Clone)]
pub struct Interception {
    pub listen: SocketAddr,
    pub ports: Vec<(u16, u16)>,
}

/// A shell script that installs the rules. Running it again replaces them.
pub fn setup_script(interception: Option<&Interception>) -> String {
    let mut out = String::new();
    let _ = writeln!(
        out,
        "#!/bin/sh\n\
         # Generated by mc-gateway. Safe to run again: it replaces its own rules.\n\
         set -eu\n\
         \n\
         ip rule show | grep -q 'fwmark {ROUTE_MARK:#x} lookup {ROUTE_TABLE}' \\\n    \
         || ip rule add fwmark {ROUTE_MARK:#x} lookup {ROUTE_TABLE}\n\
         ip route replace local default dev lo table {ROUTE_TABLE}\n\
         \n\
         # Connections the gateway handles are delivered locally, so they cross the\n\
         # INPUT chain. A host firewall that drops there (ufw's default) would stop\n\
         # every one of them, and a port rule cannot help: after Docker's DNAT the\n\
         # packet carries the container's port. Accept the gateway's mark instead.\n\
         if command -v iptables >/dev/null 2>&1; then\n    \
         iptables -C INPUT -m mark --mark {ROUTE_MARK:#x} -j ACCEPT 2>/dev/null \\\n        \
         || iptables -I INPUT 1 -m mark --mark {ROUTE_MARK:#x} -j ACCEPT\n\
         else\n    \
         echo 'mc-gateway: iptables not found; if this host filters INPUT, accept fwmark {ROUTE_MARK:#x} there' >&2\n\
         fi\n\
         \n\
         nft -f - <<'NFT'\n{}NFT\n\
         \n\
         echo 'mc-gateway: network setup installed' >&2",
        ruleset(interception)
    );
    out
}

/// A shell script that removes everything [`setup_script`] installs.
pub fn teardown_script() -> String {
    format!(
        "#!/bin/sh\n\
         # Generated by mc-gateway.\n\
         # Missing tools must fail loudly: a teardown that silently does nothing\n\
         # leaves the interception rules in place.\n\
         for tool in nft ip; do\n    \
         command -v \"$tool\" >/dev/null || {{ echo \"mc-gateway: $tool not found\" >&2; exit 1; }}\n\
         done\n\
         if nft list table ip {NFT_TABLE} >/dev/null 2>&1; then nft delete table ip {NFT_TABLE}; fi\n\
         if command -v iptables >/dev/null 2>&1; then\n    \
         while iptables -D INPUT -m mark --mark {ROUTE_MARK:#x} -j ACCEPT 2>/dev/null; do :; done\n\
         fi\n\
         while ip rule del fwmark {ROUTE_MARK:#x} lookup {ROUTE_TABLE} 2>/dev/null; do :; done\n\
         ip route flush table {ROUTE_TABLE} 2>/dev/null || true\n\
         echo 'mc-gateway: network setup removed' >&2\n"
    )
}

/// The nftables ruleset on its own.
pub fn ruleset(interception: Option<&Interception>) -> String {
    let mut out = String::new();
    // Declared and flushed first, so loading this twice does not duplicate
    // rules.
    let _ = writeln!(out, "table ip {NFT_TABLE}\nflush table ip {NFT_TABLE}\n");
    let _ = writeln!(out, "table ip {NFT_TABLE} {{");
    let _ = writeln!(out, "    chain prerouting {{");
    let _ = writeln!(out, "        type filter hook prerouting priority mangle; policy accept;");
    let _ = writeln!(out);
    let _ = writeln!(
        out,
        "        # Packets of connections the gateway is part of: deliver them locally."
    );
    let _ = writeln!(out, "        ct mark {CONN_MARK:#x} meta mark set {ROUTE_MARK:#x} accept");

    if let Some(interception) = interception {
        let ports = interception
            .ports
            .iter()
            .map(|(start, end)| {
                if start == end { start.to_string() } else { format!("{start}-{end}") }
            })
            .collect::<Vec<_>>()
            .join(", ");
        let _ = writeln!(out);
        let _ = writeln!(
            out,
            "        # New connections to the intercepted ports go to the gateway. Loopback is\n        \
             # excluded so the gateway's own connections cannot loop back into it, and\n        \
             # `tproxy` does not match at all when the gateway is not listening."
        );
        let _ = writeln!(
            out,
            "        iifname != \"lo\" fib daddr type local tcp dport {{ {ports} }} ct state new \
             tproxy to {listen} meta mark set {ROUTE_MARK:#x} ct mark set {CONN_MARK:#x} accept",
            listen = interception.listen,
        );
    }

    let _ = writeln!(out, "    }}\n");
    let _ = writeln!(out, "    chain output {{");
    let _ = writeln!(out, "        type route hook output priority mangle; policy accept;");
    let _ = writeln!(
        out,
        "        # The gateway's own transparent connections: remember them for their replies."
    );
    let _ = writeln!(out, "        meta mark {SOCKET_MARK:#x} ct mark set {CONN_MARK:#x}");
    let _ = writeln!(out, "    }}");
    let _ = writeln!(out, "}}");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn node() -> Interception {
        Interception {
            listen: "127.0.0.1:25500".parse().unwrap(),
            ports: vec![(30000, 40000), (25565, 25565)],
        }
    }

    #[test]
    fn interception_rule_names_every_range_and_the_listener() {
        let rules = ruleset(Some(&node()));
        assert!(rules.contains("tcp dport { 30000-40000, 25565 }"), "{rules}");
        assert!(rules.contains("tproxy to 127.0.0.1:25500"), "{rules}");
        assert!(rules.contains("ct state new"), "only new connections are diverted");
        assert!(rules.contains("iifname != \"lo\""), "the gateway must not intercept itself");
    }

    #[test]
    fn without_interception_only_the_return_path_is_installed() {
        let rules = ruleset(None);
        assert!(!rules.contains("tproxy"), "{rules}");
        assert!(rules.contains("meta mark 0x6d64 ct mark set 0x6d63"), "{rules}");
        assert!(rules.contains("ct mark 0x6d63 meta mark set 0x6d67"), "{rules}");
    }

    #[test]
    fn the_ruleset_replaces_itself() {
        let rules = ruleset(Some(&node()));
        assert!(rules.starts_with("table ip mcgateway\nflush table ip mcgateway"), "{rules}");
    }

    #[test]
    fn setup_and_teardown_agree_on_marks_and_table() {
        let setup = setup_script(Some(&node()));
        let teardown = teardown_script();
        for needle in ["fwmark 0x6d67 lookup 6767", "table 6767"] {
            assert!(setup.contains(needle), "setup lacks {needle}:\n{setup}");
            assert!(teardown.contains(needle), "teardown lacks {needle}:\n{teardown}");
        }
        assert!(teardown.contains("nft delete table ip mcgateway"));
        assert!(teardown.contains("command -v"), "a missing nft must not pass silently");
        let input_rule = "INPUT -m mark --mark 0x6d67 -j ACCEPT";
        assert!(setup.contains(input_rule), "setup must open INPUT for the gateway:\n{setup}");
        assert!(teardown.contains(&format!("-D {input_rule}")), "teardown must close it again");
    }
}
