//! The host network setup transparent forwarding depends on, generated from
//! the gateway's own configuration so the port range and the marks can never
//! disagree between the config file and the firewall.
//!
//! ```text
//! mc-gateway --config config.yaml --print-network-setup | sh
//! ```
//!
//! Two kinds of connection carry a conntrack mark:
//!
//! * [`INTERCEPT_MARK`] — a player's connection, handed to the gateway by
//!   `tproxy`. The player's later packets on it must reach the gateway's socket.
//! * [`BACKEND_MARK`] — a connection the gateway opened to a server from the
//!   player's address. Its sockets carry [`SOCKET_MARK`], which the `output`
//!   chain copies onto the connection. The server's replies must reach the
//!   gateway's socket.
//!
//! Both are steered by [`ROUTE_MARK`], which [`ROUTE_TABLE`] delivers locally.
//!
//! Replies to [`BACKEND_MARK`] connections are caught in two places, because
//! they come from two places: `prerouting` for a server behind a bridge (a
//! container reached through Docker's DNAT), `output` for a server on the host
//! itself (a plain process, or Docker's `docker-proxy`, which is how Docker
//! usually publishes a port on IPv6).
//!
//! The rules fail open. If the gateway is not listening, `tproxy` finds no
//! socket and does not match, so connections go straight to the server as if
//! the rules were not there. Everything is installed for IPv4 and IPv6 alike;
//! on a host without IPv6 the IPv6 parts are skipped.

use std::fmt::Write;

use crate::config::Config;

/// Set with `SO_MARK` on every transparent backend socket.
pub const SOCKET_MARK: u32 = 0x6d64;
/// Conntrack mark of an intercepted player connection.
pub const INTERCEPT_MARK: u32 = 0x6d63;
/// Conntrack mark of a connection the gateway opened to a server.
pub const BACKEND_MARK: u32 = 0x6d65;
/// Packet mark that selects [`ROUTE_TABLE`].
pub const ROUTE_MARK: u32 = 0x6d67;
/// Routing table whose only route delivers everything locally.
pub const ROUTE_TABLE: u32 = 6767;
/// nftables table name, owned entirely by the gateway.
pub const NFT_TABLE: &str = "mcgateway";

/// A shell script that installs the rules. Running it again replaces them.
pub fn setup_script(config: &Config) -> String {
    let mut out = String::new();
    let _ = write!(
        out,
        r#"#!/bin/sh
# Generated by mc-gateway. Safe to run again: it replaces its own rules.
set -eu

if [ -f /proc/net/if_inet6 ]; then has_ipv6=1; else has_ipv6=0; fi

ip rule show | grep -q 'fwmark {mark:#x} lookup {table}' \
    || ip rule add fwmark {mark:#x} lookup {table}
ip route replace local default dev lo table {table}
if [ "$has_ipv6" = 1 ]; then
    ip -6 rule show | grep -q 'fwmark {mark:#x} lookup {table}' \
        || ip -6 rule add fwmark {mark:#x} lookup {table}
    ip -6 route replace local default dev lo table {table}
fi

# Connections the gateway handles are delivered locally, so they cross the
# INPUT chain. A host firewall that drops there (ufw's default) would stop
# every one of them, and a port rule cannot help: after Docker's DNAT the
# packet carries the container's port. Accept the gateway's mark instead.
allow_input() {{
    if command -v "$1" >/dev/null 2>&1; then
        "$1" -C INPUT -m mark --mark {mark:#x} -j ACCEPT 2>/dev/null \
            || "$1" -I INPUT 1 -m mark --mark {mark:#x} -j ACCEPT
    else
        echo "mc-gateway: $1 not found; if this host filters INPUT, accept fwmark {mark:#x} there" >&2
    fi
}}
allow_input iptables
if [ "$has_ipv6" = 1 ]; then allow_input ip6tables; fi

# Replaced by an inet table below; removed here after an upgrade.
nft delete table ip {nft_table} 2>/dev/null || true

nft -f - <<'NFT'
{rules}NFT

echo 'mc-gateway: network setup installed' >&2
"#,
        mark = ROUTE_MARK,
        table = ROUTE_TABLE,
        nft_table = NFT_TABLE,
        rules = ruleset(config),
    );
    out
}

/// A shell script that removes everything [`setup_script`] installs.
pub fn teardown_script() -> String {
    format!(
        r#"#!/bin/sh
# Generated by mc-gateway.
# Missing tools must fail loudly: a teardown that silently does nothing leaves
# the interception rules in place.
for tool in nft ip; do
    command -v "$tool" >/dev/null || {{ echo "mc-gateway: $tool not found" >&2; exit 1; }}
done

for family in inet ip; do
    if nft list table $family {nft_table} >/dev/null 2>&1; then nft delete table $family {nft_table}; fi
done

while ip rule del fwmark {mark:#x} lookup {table} 2>/dev/null; do :; done
ip route flush table {table} 2>/dev/null || true
if [ -f /proc/net/if_inet6 ]; then
    while ip -6 rule del fwmark {mark:#x} lookup {table} 2>/dev/null; do :; done
    ip -6 route flush table {table} 2>/dev/null || true
fi

for tool in iptables ip6tables; do
    if command -v "$tool" >/dev/null 2>&1; then
        while "$tool" -D INPUT -m mark --mark {mark:#x} -j ACCEPT 2>/dev/null; do :; done
    fi
done

echo 'mc-gateway: network setup removed' >&2
"#,
        mark = ROUTE_MARK,
        table = ROUTE_TABLE,
        nft_table = NFT_TABLE,
    )
}

/// The nftables ruleset on its own.
pub fn ruleset(config: &Config) -> String {
    let mut out = String::new();
    // Declared and flushed first, so loading this twice does not duplicate
    // rules.
    let _ = writeln!(
        out,
        "table inet {NFT_TABLE}\nflush table inet {NFT_TABLE}\n"
    );
    let _ = write!(
        out,
        r#"table inet {NFT_TABLE} {{
    chain prerouting {{
        type filter hook prerouting priority mangle; policy accept;

        # The player's packets on a connection the gateway intercepted.
        ct mark {INTERCEPT_MARK:#x} ct direction original meta mark set {ROUTE_MARK:#x} accept
        # A server's replies to a connection the gateway opened, arriving from a
        # bridge or the network.
        ct mark {BACKEND_MARK:#x} ct direction reply meta mark set {ROUTE_MARK:#x} accept
"#
    );

    {
        let ports = config
            .ports
            .iter()
            .map(ToString::to_string)
            .collect::<Vec<_>>()
            .join(", ");
        let _ = write!(
            out,
            r#"
        # New connections to the intercepted ports go to the gateway. Loopback is
        # excluded so the gateway's own connections cannot loop back into it, and
        # `tproxy` does not match at all when the gateway is not listening.
"#
        );
        let _ = writeln!(
            out,
            "        iifname != \"lo\" fib daddr type local tcp dport {{ {ports} }} ct state new \
             meta nfproto ipv4 tproxy ip to {listen} \
             meta mark set {ROUTE_MARK:#x} ct mark set {INTERCEPT_MARK:#x} accept",
            listen = config.listen,
        );
        if let Some(listen_v6) = config.listen_v6 {
            let _ = writeln!(
                out,
                "        iifname != \"lo\" fib daddr type local tcp dport {{ {ports} }} ct state new \
                 meta nfproto ipv6 tproxy ip6 to {listen_v6} \
                 meta mark set {ROUTE_MARK:#x} ct mark set {INTERCEPT_MARK:#x} accept",
            );
        }
    }

    let _ = write!(
        out,
        r#"    }}

    chain output {{
        type route hook output priority mangle; policy accept;

        # The gateway's own transparent connections to servers.
        meta mark {SOCKET_MARK:#x} ct mark set {BACKEND_MARK:#x}
        # A server's replies generated on this host — a plain process, or
        # docker-proxy — are re-routed to the gateway as well.
        ct mark {BACKEND_MARK:#x} ct direction reply meta mark set {ROUTE_MARK:#x}
    }}
}}
"#
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn node(extra: &str) -> Config {
        Config::parse(
            &format!("ports: [\"30000-40000\", 25565]\nmotd: {{line2: x}}\n{extra}"),
            "test",
        )
        .unwrap()
        .config
    }

    #[test]
    fn interception_covers_both_families() {
        let rules = ruleset(&node(""));
        assert!(
            rules.contains("tcp dport { 30000-40000, 25565 }"),
            "{rules}"
        );
        assert!(
            rules.contains("meta nfproto ipv4 tproxy ip to 127.0.0.1:25500"),
            "{rules}"
        );
        assert!(
            rules.contains("meta nfproto ipv6 tproxy ip6 to [::1]:25500"),
            "{rules}"
        );
        assert!(
            rules.contains("ct state new"),
            "only new connections are diverted"
        );
        assert!(
            rules.contains("iifname != \"lo\""),
            "the gateway must not intercept itself"
        );
    }

    #[test]
    fn ipv6_interception_can_be_turned_off() {
        let rules = ruleset(&node("listen_v6: null\n"));
        assert!(rules.contains("tproxy ip to"), "{rules}");
        assert!(!rules.contains("tproxy ip6"), "{rules}");
    }

    #[test]
    fn server_replies_are_steered_back_from_the_network_and_from_the_host() {
        let rules = ruleset(&node(""));
        let (prerouting, output) = rules.split_at(rules.find("chain output").unwrap());
        let steer = "ct mark 0x6d65 ct direction reply meta mark set 0x6d67";
        assert!(prerouting.contains(steer), "replies via a bridge:\n{rules}");
        assert!(
            output.contains(steer),
            "replies from docker-proxy or a host process:\n{rules}"
        );
        assert!(
            output.contains("meta mark 0x6d64 ct mark set 0x6d65"),
            "{rules}"
        );
    }

    #[test]
    fn the_players_own_replies_are_not_rerouted() {
        // The reply direction of an intercepted connection is the gateway talking
        // to the player; steering it locally would black-hole the session.
        assert!(!ruleset(&node("")).contains("ct mark 0x6d63 ct direction reply"));
    }

    #[test]
    fn the_ruleset_replaces_itself() {
        assert!(ruleset(&node("")).starts_with("table inet mcgateway\nflush table inet mcgateway"));
    }

    #[test]
    fn setup_and_teardown_agree() {
        let setup = setup_script(&node(""));
        let teardown = teardown_script();
        for needle in ["fwmark 0x6d67 lookup 6767", "table 6767", "ip -6 rule"] {
            assert!(setup.contains(needle), "setup lacks {needle}:\n{setup}");
            assert!(
                teardown.contains(needle),
                "teardown lacks {needle}:\n{teardown}"
            );
        }
        assert!(setup.contains("allow_input iptables") && setup.contains("allow_input ip6tables"));
        assert!(teardown.contains("-D INPUT -m mark --mark 0x6d67 -j ACCEPT"));
        assert!(
            teardown.contains("command -v"),
            "a missing nft must not pass silently"
        );
    }
}
